name: stamp

services:
  app:
    container_name: "web_stamp"
    build: .
    depends_on:
      - db
    restart: "unless-stopped"
    ports:
      - "3000:3000"
      - "3080:3080"
    volumes:
      - /files/stamp/files:/stamp/files
      - /files/stamp/logs:/stamp/logs
  db:
    image: "mongo"
    container_name: "db_stamp"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    volumes:
      - /files/db/stamp:/data/db

