name: stamp

services:
  app:
    container_name: "web_stamp"
    env_file: app.env
    build: .
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 250M
        reservations:
          cpus: "0.5"
          memory: 140M
    depends_on:
      - db
    restart: "unless-stopped"
    ports:
      - "3000:3000"
      - "3080:3080"
    volumes:
      - /files/stamp/files:/stamp/files
      - /files/stamp/logs:/stamp/logs
  db:
    container_name: "db_stamp"
    image: "mongo"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 350M
        reservations:
          cpus: "1.0"
          memory: 250M
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    volumes:
      - /files/db/stamp:/data/db

